### PR TITLE
Add a tooltip to actions in WrapperWidgetUI

### PR DESCRIPTION
**Pull request by builtbyedgar**

### CODE REVIEW

**Comment by builtbyedgar** [comment]
With icon no, sorry. With tooltip

**Review by neokore — APPROVED** [review]
LGTM
Add an entry to the changelog file and it is ready!

**Comment by VictorVelarde** [comment]
As Raul says: refresh the branch with master, and use the 'not released' section in CHANGELOG.md to add a note like:

- Add a tooltip to actions in WrapperWidgetUI [#40](https://github.com/CartoDB/carto-react-lib/pull/40)

**Comment by VictorVelarde** [comment]
@neokore Why develop and not master?

**Comment by neokore** [comment]
This PR is a bit old and was hard to rebase, so @builtbyedgar created a new one (https://github.com/CartoDB/carto-react-lib/pull/56). I'll close this one.

**Pull request closed without merging**
