### PR TITLE
Declare peer dependencies & reduce library bundle size

### PR DESCRIPTION
**Pull request by juandjara**
Related story: https://app.clubhouse.io/cartoteam/story/130033/lib-improve-export-carto-lib

### CODE REVIEW

**Review by albertoarana — APPROVED** [review]

**Comment by alasarr** [comment]
@juandjara could you check the conflicts?

**Comment by juandjara** [comment]
Done, merged master into this branch and resolved the conflicts

**Comment by juandjara** [comment]
@alasarr ok now rebase is sucessfully done without conflicts

**Comment by VictorVelarde** [comment]
Checking this, I'm gonna create another PR in the template, to manage the change

**Review by VictorVelarde — APPROVED** [review]
👍🏻

**Pull request merged**
